### ISSUE TITLE
Delete reading Products

### ISSUE THREAD

**Issue by yamanoku** [yamanoku/reading#1000]
## Why
- I stopped looking at it myself.
- I'm trying to use [Scrapbox](https://scrapbox.io/yamanoku/) to link to things related to the news in addition to what I've seen.
- Slack for free accounts now deletes data after 90 days.
  - Instead, I try to accumulate it on my personal Discord.
- I'd like to open up the IFTTT framework that I use for Twitter and Slack integration.

## Todo
- [x] Close all issues except this one
- [x] Delete renovate settings
- [x] Delete Netlify hosting
- [x] Delete CircleCI integration
- [x] Delete subdomain
- [x] Delete Slack Token & Slack App
- [x] Delete IFTTT integration
- [x] Delete product source (ignore archives) #1001 
- [x] Update README #1001
